### ISSUE TITLE
Fails to honor ruby executable path when specified in settings

### ISSUE THREAD

**Issue by mojason-81** [AtomLinter/linter-erb#37]
I've overridden the ruby executable path and manually entered in:

`/home/jason/.rvm/rubies/ruby-2.3.0/bin/ruby`

However, I still receive the following error:

```
Error: /usr/bin/env: ruby: No such file or directory
    at parameters.exit (/home/jason/.atom/packages/linter-erb/node_modules/atom-linter/lib/helpers.js:47:27)
    at triggerExitCallback (/opt/atom/resources/app.asar/src/buffered-process.js:213:47)
    at /opt/atom/resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/opt/atom/resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

Also, the directions in the README say that the rubyExecutablePath defaults to erb.  I'm thinking this is a typo.

Setting my executable path for linter-ruby in the same manner works fine, but not for linter-erb.

- Ubuntu: 15.10
- kernel: 4.2.0-34
- Atom: 1.6.0
- linter-erb: 1.0.2

**edit**
[Link to StackOverflow discussion.](http://stackoverflow.com/questions/36511302/atom-linter-erb-failing-with-error-usr-bin-env-ruby-no-such-file-or-directo)

**Comment by Arcanemagus** [comment]
Nothing about this package deals with `/usr/bin/env`, so I'm _guessing_ that your `/home/jason/.rvm/rubies/ruby-2.3.0/bin/ruby` is actually a shell script that attempts to call the real `ruby` binary, which may only work in interactive shells?

Without knowing what is in that file though it's pretty hard to diagnose, it seems you have already been directed at using the wrapper script, which is a necessity if you are using `rvm` as by default it uses shell macro expansion to run the proper program... which doesn't work when not being ran from a shell environment.

**Comment by mojason-81** [comment]
@Arcanemagus Does this help at all?  It appears to me that it *is* the ruby executable which would make sense since this works when pointing linter-ruby to the same file.  However, I'm that that much of a guru on these matters.

```
$ file /home/jason/.rvm/rubies/ruby-2.3.0/bin/ruby
/home/jason/.rvm/rubies/ruby-2.3.0/bin/ruby: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=ca8f0b8afb2599c971adf419fbb6bc7134d3f4d0, not stripped
```

> which doesn't work when not being ran from a shell environment.

Am I understanding that correctly as "using the wrapper script probably won't work in this scenario" ?

Thanks for the help on this.

**Comment by ricardograca** [comment]
If you set the default ruby like this:

    rvm --default use 2.3.0

does it change anything? (Assuming 2.3.0 will point to the same ruby that you entered in the package settings)

You can revert that change with:

    rvm use system

**Comment by mojason-81** [comment]
2.3.0 is already set as the default in rvm.  So this would have no affect.  Here's a bit more output.

```
$ which ruby
/home/jason/.rvm/rubies/ruby-2.3.0/bin/ruby

$ which erb
/home/jason/.rvm/rubies/ruby-2.3.0/bin/erb

$ rvm list

rvm rubies

   ruby-2.2.2 [ x86_64 ]
=* ruby-2.3.0 [ x86_64 ]

# => - current
# =* - current && default
#  * - default
```

Ruby was not installed prior to me intalling rvm and running `rvm install 2.3.0` so running `rvm use system`  ends up with no output from `which ruby` since there was never a "system" ruby installed.
No issues with erb, just ruby.  And like I stated before, linter-ruby has no problems finding and using the excuteable for ruby when specified in this same manner.

**Comment by ricardograca** [comment]
Interesting. It's definitely related to your environment, but no idea what the actual problem is. If you don't manually override the ruby executable path does it work properly?

**Comment by mojason-81** [comment]
@ricardograca Sorry for the delayed response.

I get the same error regardless if I override it or not.

**Comment by ricardograca** [comment]
Did you change the Atom launcher file? It's located in `/usr/share/applications`. Do you have a custom launcher file for Atom in `~/.local/share/applications`?

I don't have a clear idea of what could be wrong here, since the only difference from the `linter-erb` side between the calls to `erb` and `ruby` is that `ruby` is called from within a promise handler, but that same code works perfectly fine in my system with Ubuntu 15.04 and ruby 2.0.0.

I've looked at the [exec helper](https://github.com/steelbrain/exec) and there's no mention of `/usr/bin/env` anywhere. Coupled with the fact that no one else complained about this problem (and you're probably not the only person running `linter-erb` on Ubuntu 15.10) makes me think this is almost certainly a problem on your side, related to rvm or something else. Maybe you're missing some wrappers, or maybe something changed in rvm and broke your config but only on non-interactive shells.

In any case, there's apparently nothing wrong in `linter-erb` that could cause what you describe, and I'm all out of ideas on what could be wrong and where to look, so I'm going to assume this is not a problem with `linter-erb`, but if you can find the actual problem and it turns out to be indeed in this package then I'll definitely fix it.

**Comment by ricardograca** [comment]
Closing this due to lack of activity. If you have any more information to add we can reopen this issue.

**Comment by jmfederico** [comment]
Hi, reopening this issue with the culprit and a solution found.

When spawning _erb_ and _ruby_ proceses, **cwd** is only passed to _erb_, but not to ruby.
This causes erb-linter to always use the system global ruby, insted of the projects (or user) ruby.

The solution is to also pass _cwd_ to the ruby call.

I've created a pull request #92

**Comment by jmfederico** [comment]
Hi, culprit and a solution found.

When spawning erb and ruby proceses, cwd is only passed to erb, but not to ruby.
This causes erb-linter to always use the system global ruby, insted of the projects (or user) ruby.

The solution is to also pass cwd to the ruby call.

I've created a pull request #92
