### ISSUE TITLE
Uncaught Error: This socket has been ended by the other party

### ISSUE THREAD

**Issue by djpowers** [AtomLinter/linter-erb#4]
1. From a Project Find Results page, I opened a file.
2. Without any further interaction, I had several instances of the same error triggered.

Interestingly, while trying to duplicate the issue, I'm now consistently receiving this previously reported error: https://github.com/atom/atom/issues/4708

**Atom Version**: 0.175.0
**System**: Mac OS X 10.9.5
**Thrown From**: [linter-erb](https://github.com/AtomLinter/linter-erb) package, v0.0.3

### Stack Trace

Uncaught Error: This socket has been ended by the other party

```
At events.js:85

Error: This socket has been ended by the other party
  at Socket.writeAfterFIN [as write] (net.js:282:12)
  at erbStdout (/Users/dpowers/.atom/packages/linter-erb/lib/linter-erb.coffee:54:33)
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:137:13)
  at Socket.emit (events.js:107:17)
  at readableAddChunk (_stream_readable.js:161:16)
  at Socket.Readable.push (_stream_readable.js:125:10)
  at Pipe.onread (net.js:522:20)

```

### Commands

```
     -4:08.5 snippets:next-tab-stop (atom-text-editor.editor.vim-mode.command-mode)
     -4:08.5 snippets:expand (atom-text-editor.editor.vim-mode.command-mode)
     -4:08.5 editor:indent (atom-text-editor.editor.vim-mode.command-mode)
     -4:06.1 core:move-down (atom-text-editor.editor.vim-mode.command-mode)
     -4:05.6 editor:newline-below (atom-text-editor.editor.vim-mode.command-mode)
     -4:04.0 core:backspace (atom-text-editor.editor.vim-mode.command-mode)
     -4:02.0 vim-mode:activate-command-mode (atom-text-editor.editor.vim-mode.command-mode)
     -4:01.6 core:save (atom-text-editor.editor.vim-mode.command-mode)
     -3:50.2 core:undo (atom-text-editor.editor.vim-mode.command-mode)
     -3:49.1 core:save (atom-text-editor.editor.vim-mode.command-mode)
     -1:45.9 vim-mode:move-up (atom-text-editor.editor.vim-mode.command-mode)
  4x -1:44.1 pane:show-next-item (atom-text-editor.editor.vim-mode.command-mode)
  2x -1:41.5 pane:show-previous-item (atom-text-editor.editor.vim-mode.command-mode)
  3x -1:30.9 core:close (atom-text-editor.editor.vim-mode.visual-mode)
 11x -0:05.8 core:move-up (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
     -0:00.0 core:confirm (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "whitespace",
      "linter-scss-lint"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.4.0
linter, v0.10.0
linter-coffeelint, v0.1.7
linter-erb, v0.0.3
linter-jshint, v0.1.0
linter-ruby, v0.1.4
minimap, v3.5.6
vim-mode, v0.29.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by ahmetabdi** [comment]
:+1:

**Comment by djpowers** [comment]
I believe this problem has also been resolved (probably in atom/notifications#62). I'll reopen if I see it again.

**Comment by pinny87** [comment]
I am now also receiving this error message.

Let me know if you want any information.

1. Open erb view file
2. Save erb view file

**Atom Version**: 1.0.0
**System**: Ubuntu 15.04
**Thrown From**: [linter-erb](https://github.com/AtomLinter/linter-erb) package, v0.1.1


### Stack Trace

Uncaught Error: This socket has been ended by the other party

```
At events.js:141

Error: This socket has been ended by the other party
  at Socket.writeAfterFIN [as write] (net.js:275:12)
  at /home/dylan/.atom/packages/linter-erb/lib/linter-erb.coffee:58:33
  at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:85:13)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:109:10)
  at Pipe.onread (net.js:517:20)

```

### Commands

```
  3x -0:28.2.0 core:close (atom-text-editor.editor.is-focused)
     -0:25 tree-view:toggle (atom-text-editor.editor.is-focused)
     -0:15.5.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:01.1.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "followSymlinks": false
  },
  "linter-erb": {
    "erbExecutablePath": "/home/dylan/.rbenv/shims/erb"
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
atom-beautify, v0.28.7
autocomplete-paths, v1.0.2
color-picker, v2.0.7
docblockr, v0.7.2
editorconfig, v1.0.1
emmet, v2.3.11
file-icons, v1.5.8
language-docker, v1.1.3
language-gitignore, v0.2.0
language-html-swig, v2.0.1
language-nginx, v0.5.3
linter, v1.1.0
linter-bootlint, v0.0.6
linter-csslint, v0.0.14
linter-erb, v0.1.1
linter-eslint, v1.0.11
linter-handlebars, v2.0.0
linter-htmlhint, v0.0.16
linter-js-standard, v0.3.0
linter-js-yaml, v1.1.1
linter-jscs, v1.12.0
linter-jshint, v0.1.7
linter-jsxhint, v0.1.2
linter-php, v0.0.15
linter-phpcs, v0.0.15
linter-phpmd, v0.0.11
linter-reek, v2.0.0
linter-rubocop, v0.2.7
linter-scss-lint, v1.0.5
linter-tidy, v1.0.1
linter-xmllint, v0.0.7
minimap, v4.10.1
pigments, v0.8.2
project-manager, v1.15.10
react, v0.12.3

# Dev
No dev packages
```

**Comment by djpowers** [comment]
I actually ran into this again myself.

[Enter steps to reproduce below:]

1.Edit conditional statement within ERB tag `<% %>`

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: write EPIPE

```
At events.js:141

Error: write EPIPE
    at Object.exports._errnoException (util.js:734:11)
    at exports._exceptionWithHostPort (util.js:757:20)
    at WriteWrap.afterWrite (net.js:753:14)
    at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.RemoteMemberFunction [as getPosition] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:110:29)
    at Atom.module.exports.Atom.getWindowDimensions (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:530:29)
    at Atom.module.exports.Atom.storeDefaultWindowDimensions (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:563:25)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:104:21
    at handler (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:115:32)
    at jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
```

### Commands

```
     -4:09.4.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -4:09.2.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.visual-mode.is-focused)
     -4:09.1.0 vim-mode:reset-normal-mode (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -4:08.8.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -4:07.3.0 command-palette:toggle (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -4:06.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:06.1.0 open-on-github:blame (atom-text-editor.editor.vim-mode.normal-mode)
  2x -1:33 vim-mode:reset-normal-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -0:09.3.0 pane:show-next-item (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  4x -0:06.5.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -0:05.8.0 vim-mode:move-to-next-word (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:04.9.0 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:04.3.0 editor:select-to-end-of-line (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:02.9.0 editor:select-to-beginning-of-word (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:02.2.0 core:select-left (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:01.7.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "whitespace"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 17
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.11
linter, v1.2.4
linter-coffeelint, v1.0.0
linter-erb, v0.1.1
linter-jshint, v1.1.4
linter-ruby, v0.1.6
linter-scss-lint, v1.0.5
minimap, v4.12.0
symbol-gen, v1.0.0
vim-mode, v0.57.0

# Dev
No dev packages
```

**Comment by graemeboy** [comment]
:thumbsup:

**Comment by Arcanemagus** [comment]
Marking this as closed, the linter needs a complete re-write before it will ever run, as such this will likely be a non-issue once that is completed.
